baseURL = 'https://zcheng-li.github.io'
languageCode = 'en-us'
title = 'ZCHENG LI'
theme = "hugo-book"
# markup.goldmark.renderer.unsafe=true

# Multilingual
defaultContentLanguage = 'zh-CN'
[languages]
  [languages.zh-cn]
    weight = 3
    languageCode = "zh-CN"
    languageName = "简体中文"
  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"

[params]
    BookRepo = 'https://github.com/alex-shpak/hugo-book'
    fancybox = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true