baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ZCHENG LI'
theme = "hugo-book"
markup.goldmark.renderer.unsafe=true

# Multilingual
defaultContentLanguage = 'en'
[languages]
  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"

  [languages.zh-cn]
    weight = 3
    languageCode = "zh-CN"
    languageName = "简体中文"

[params]
    BookRepo = 'https://github.com/alex-shpak/hugo-book'
    fancybox = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
